name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: petrol-ethra-adikkanam
  PYTHON_VERSION: '3.9'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Release'
      url: ${{ steps.site_url.outputs.https_url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          
      - name: 'Set site URL'
        id: site_url
        shell: pwsh
        env:
          site_url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        run: |
          $https_url = ${env:site_url}.replace('http', 'https')
          Write-Host "URL updated: $https_url"
          Write-Host "::set-output name=https_url::$( $https_url)"
